
package com.sahand.setting.proxy.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-417-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SettingReportImplService", targetNamespace = "http://service.setting.sahand.com/", wsdlLocation = "http://192.168.7.192:8180/setting-service/SettingReportImpl?wsdl")
public class SettingReportImplService
    extends Service
{

    private final static URL SETTINGREPORTIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sahand.setting.proxy.service.SettingReportImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sahand.setting.proxy.service.SettingReportImplService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.7.192:8180/setting-service/SettingReportImpl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.7.192:8180/setting-service/SettingReportImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SETTINGREPORTIMPLSERVICE_WSDL_LOCATION = url;
    }

    public SettingReportImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SettingReportImplService() {
        super(SETTINGREPORTIMPLSERVICE_WSDL_LOCATION, new QName("http://service.setting.sahand.com/", "SettingReportImplService"));
    }

    /**
     * 
     * @return
     *     returns SettingReportImpl
     */
    @WebEndpoint(name = "SettingReportImplPort")
    public SettingReportImpl getSettingReportImplPort() {
        return super.getPort(new QName("http://service.setting.sahand.com/", "SettingReportImplPort"), SettingReportImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SettingReportImpl
     */
    @WebEndpoint(name = "SettingReportImplPort")
    public SettingReportImpl getSettingReportImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.setting.sahand.com/", "SettingReportImplPort"), SettingReportImpl.class, features);
    }

}
