
package com.sahand.setting.proxy.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-417-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SettingReportImpl", targetNamespace = "http://service.setting.sahand.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SettingReportImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sahand.setting.proxy.service.SettingReportResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadSystemLookup", targetNamespace = "http://service.setting.sahand.com/", className = "com.sahand.setting.proxy.service.LoadSystemLookup")
    @ResponseWrapper(localName = "loadSystemLookupResponse", targetNamespace = "http://service.setting.sahand.com/", className = "com.sahand.setting.proxy.service.LoadSystemLookupResponse")
    public SettingReportResponse loadSystemLookup(
        @WebParam(name = "arg0", targetNamespace = "")
        SettingReportRequest arg0);

}
